### ISSUE TITLE
ImportError: cannot import name unpack_apply_message

### ISSUE THREAD

**Issue by jedie** [kaazoo/DrQueueIPython#5]
Maybe IPython has changed his API?

```
(DrQueue_env)jens@vm:~/DrQueue_env$ drqueue 
Traceback (most recent call last):
  File "/home/jens/DrQueue_env/bin/drqueue", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/jens/DrQueue_env/src/drqueueipython/bin/drqueue", line 16, in <module>
    import DrQueue
  File "/home/jens/DrQueue_env/src/drqueueipython/DrQueue/__init__.py", line 19, in <module>
    from .client import Client
  File "/home/jens/DrQueue_env/src/drqueueipython/DrQueue/client.py", line 19, in <module>
    from IPython.parallel.util import unpack_apply_message
ImportError: cannot import name unpack_apply_message
```

I found **IPython.kernel.zmq.serialize.unpack_apply_message()** see:
https://ipython.org/ipython-doc/dev/api/generated/IPython.kernel.zmq.serialize.html#IPython.kernel.zmq.serialize.unpack_apply_message

**Comment by jedie** [comment]
I just try a downgrade of ipython and it looks like a useable work-a-round:

```
(DrQueue_env)jens@vm:~/DrQueue_env$ pip install "ipython<3"
Collecting ipython<3
  Downloading ipython-2.4.1-py27-none-any.whl (2.8MB)
    100% |████████████████████████████████| 2.8MB 187kB/s 
Installing collected packages: ipython
  Found existing installation: ipython 3.2.1
    Uninstalling ipython-3.2.1:
      Successfully uninstalled ipython-3.2.1
Successfully installed ipython-2.4.1
(DrQueue_env)jens@vm:~/DrQueue_env$ drqueue 
usage: drqueue [-h] [-v] [--no-ssh]
               {job,task,computer,security,master,slave} ...
drqueue: error: too few arguments
```
